// Generated by CoffeeScript 1.7.1
(function() {
  var moveBead;

  moveBead = function(e) {
    var col, parent, total;
    $('.bead').unbind('click', moveBead);
    col = $(this).data('col');
    parent = $(this).parents('div.divide');
    parent.find(".bead:not(.inactive)[data-col=" + col + "]").addClass('active');
    $(this).removeClass('active');
    $('.bead.active').bind('click', moveBead);
    total = 0;
    col = 0;
    while (col <= $('.row .bead').length) {
      $(".earth .bead[data-col=" + col + "]").each(function() {
        if ($(this).hasClass('active')) {
          if (col === 0) {
            return total += 1;
          } else if (col === 1) {
            return total += 1 * 10;
          } else if (col === 2) {
            return total += 1 * 10 * 6;
          } else if (col === 3) {
            return total += 1 * 10 * 6 * 10;
          } else if (col === 4) {
            return total += 1 * 10 * 6 * 10 * 6;
          } else if (col === 5) {
            return total += 1 * 10 * 6 * 10 * 6 * 10;
          }
        } else {
          return false;
        }
      });
      $($(".heaven .bead[data-col=" + col + "]").get().reverse()).each(function() {
        if ($(this).hasClass('active')) {
          if (col === 0) {
            return total += 10 / 2;
          } else if (col === 1) {
            return total += (10 * 6) / 2;
          } else if (col === 2) {
            return total += (10 * 6 * 10) / 2;
          } else if (col === 3) {
            return total += (10 * 6 * 10 * 6) / 2;
          } else if (col === 4) {
            return total += (10 * 6 * 10 * 6 * 10) / 2;
          } else if (col === 5) {
            return total += (10 * 6 * 10 * 6 * 10 * 6) / 2;
          }
        } else {
          return false;
        }
      });
      col++;
    }
    return $('.total').text(String(total).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,"));
  };

  jQuery(function() {
    $('.heaven .row:not(:last) .bead, .earth .row:not(:first) .bead').addClass('active');
    $('.earth > div:nth-child(4) > div:nth-child(1)').removeClass('active').addClass('inactive');
    $('.earth > div:nth-child(5) > div:nth-child(1)').removeClass('active').addClass('inactive');
    $('.earth > div:nth-child(4) > div:nth-child(3)').removeClass('active').addClass('inactive');
    $('.earth > div:nth-child(5) > div:nth-child(3)').removeClass('active').addClass('inactive');
    $('.earth > div:nth-child(4) > div:nth-child(5)').removeClass('active').addClass('inactive');
    $('.earth > div:nth-child(5) > div:nth-child(5)').removeClass('active').addClass('inactive');
    $('.total').text(0);
    return $(".bead").bind('click', moveBead);
  });

}).call(this);
